roles/unicorn/templates/unicorn_init.j2

Provide success message for upgrade task, so that `fairfood/script/deploy` can determine success or not.

Provide success message for upgrade

---

group_vars/all.yml

https://github.com/ceresfairfood/fairfood-issues/issues/517
There are over 100 requests per month for PHP scripts. This rule should save us some resources and unclutter our log files.
If a user accidentally went to a URL ending in `.php` they will see a quicker but less beautiful error page.
Before:
After:
But since this is extremely unlikely, I wouldn't add complexity and server load to our application to show something better here. This can be improved if we get that feedback though.
This has been added to the staging server.

Block scanning for scripts efficiently

---

roles/unicorn/templates/unicorn.rb.j2

It's in the config file because I couldn't figure out how to wrap the gem.
https://github.com/ceresfairfood/fairfood-issues/issues/1881

Mokey-patch in Unicorn config to log a stack trace on timeout

---

group_vars/all.yml
roles/mail/tasks/main.yml

I came across this old issue and thought 'hey, that sounds easy', so I did it.
However it sends an email everytime I accidentally type `sudo` as the fairfood user. Hopefully that will be less frequent if I get in the habit of switching to `root` anyway..
ceresfairfood/fairfood-install#13

Forward system messages to IT email address

---

roles/mysql/templates/my.cnf

We saw this:
Info: Using unique option prefix 'database' is error-prone and can break in the future. Please use the full name 'databases' instead.
Warning: mysqldump: ignoring option '--databases' due to invalid value 'fairfood_production'
We thought that db2fog was outdated but the offending option came from
out own .my.cnf file. It contained the `database` option so that we
don't have to type the database name to connect on the console.
But while the `mysql` command supports that option, `mysqldump` doesn't
and was complaining about it. This problem is solved by being more
specific in the config file.
[ceresfairfood/fairfood-issues#](https://github.com/ceresfairfood/fairfood-issues/issues/2125)

Avoid mysqldump warning about database prefix

---

roles/fairfood/templates/post-receive.j2

We tried to be clever and only reload unicorn when no gems changed. It's
faster. But that logic can fail if a previous deployment failed for
another reason. Let's be safe an always upgrade.
ceresfairfood/fairfood-issues#2183
I changed this on staging and production.

Always upgrade unicorn instead of just reloading

---

README.md
Vagrantfile
collectd-wormly.yml
hosts
metabase.yml

This is a breaking change. Your old VM will have a different SSH key
to this config. You can override it on the command line or create a new
VM.
I'm currently working on ofn-install and found this config much easier.

Simplify vagrant hosts config

---

roles/fairfood/templates/post-receive.j2

Future versions will stop supporting the extra parameters. This avoids
deprecation warnings.
I noticed this when deploying Ruby 3 with new bundler.
I changed this on staging and production already.

Configure bundler via its new API

---

roles/fairfood/templates/post-receive.j2

Instead of filtering them.
I just had a look at `man bundle-config` out of curiosity and found this.

Suppress bundler's "Using" messages

---

roles/mysql/tasks/main.yml

Logging to help debug any future occurrences of:
ceresfairfood/fairfood-issues#2229
Tested and enabled on vagrant and staging. I've manually set on prod, and it will require a service restart. Will communicate with team and could schedule for this afternoon.

Enable mariadb logging to file

---

roles/fairfood-dependencies/tasks/main.yml

New Rubies don't bundle libyaml any more. Instead they rely on the operating system to provide it which is more efficient. Just means that we need to install another dependency.
* https://github.com/ceresfairfood/fairfood/pull/1927

Install libyaml-dev for Ruby 3.2

---

group_vars/all.yml

* Closes ceresfairfood/fairfood-issues#2424
Deployed on staging:
```
TASK [unicorn : copy unicorn files] ********************************************************************************************************************************************************************************************************
ok: [staging.ceresfairfood.org.au] => (item={'src': 'unicorn_init.j2', 'dest': '/etc/init.d/unicorn_fairfood', 'mode': '0744', 'owner': 'fairfood', 'group': 'fairfood'})
changed: [staging.ceresfairfood.org.au] => (item={'src': 'unicorn.rb.j2', 'dest': '/srv/fairfood/unicorn.rb', 'mode': '0744', 'owner': 'fairfood', 'group': 'fairfood'})
...
TASK [jdauphant.nginx : Create the configurations for sites] ****************************************************************************************** …
```

Increase Unicorn and nginx timeouts

---

roles/config/README.md
roles/config/handlers/main.yml
roles/config/tasks/main.yml
site.yml

to avoid hard drive filling up! 
This config freed up about 1.3gb on staging. 
I manually ran the new tasks on staging.
I'll manually apply to prod once merged.
This might be worth doing for the Ubuntu OFN servers too.

Set journal log size limit

---

group_vars/all.yml
site.yml

Required in order to access products.json on the Wordpress site, to provide products search with autocomplete.
- ceresfairfood/fairfood-issues#2440
I think deploying with ansible is too risky (may affect WP site), so will manually copy in these changes on prod.

Allow CORS for any subdomains

---

roles/fairfood/tasks/main.yml
roles/fairfood/templates/bundle-config.j2
roles/fairfood/templates/post-receive.j2

And set bundle config once instead of every deploy. 
this reduces one line of unnecessary console output, yay! Before:
```
remote: You are replacing the current local value of without, which is currently "development:test"
```
Now slightly cleaner:
```
remote: Already up-to-date: Bundler version 2.6.3
remote: Bundle complete! 86 Gemfile dependencies, 176 gems now installed.
remote: Gems in the groups 'development', 'test' and 'code_quality' were not installed.
remote: Bundled gems are installed into `/srv/fairfood/.gem`
remote: 2 installed gems you directly depend on are looking for funding.
```

Don't install code_quality gems on servers 

---

README.md
ansible.cfg
group_vars/all.yml
hosts

- arising from ceresfairfood/fairfood-issues#2627
`/favicon.ico` is requested a lot, and is being routed by Rails, using unnecessary resources. Our favicon is defined in the HTML using png which is a way better format. But I think it's some kind of client optimisation that looks ahead when preparing to navigate to a page before it has parsed (or perhaps even requested) the HTML. 
So we can add a hint here which says exactly what the HTML says: load `/favicon.png`.
Also while provisioning I missed a few little niceties from ofn-install and copied them over.

Favicon redirect

---

roles/fairfood/templates/post-receive.j2

This will remove any gem versions that are no longer used. I ran it on both staging and prod. It cleaned up about 550mb for the current ruby version. We don't have a way of automatically cleaning up old ruby versions, so it would mean they end up smaller too.
The only risk I can think of is if we needed to revert a gem upgrade after deployment, and for some reason couldn't download/build it again. That seems highly unlikely.

Clean up unused gems after deploy

---

group_vars/all.yml
roles/geolimit/tasks/main.yml
site.yml

https://github.com/ceresfairfood/fairfood-issues/issues/2615
It restricts overseas traffic to 70 requests at a time and then delays to a rate our app can easily handle. When sending 80 requests from overseas, 9 got dropped straight away and 71 were processed within 30 seconds while the app was still responsive and fast from within Australia.
One problem I was facing here is the secret license key. How do we supply that? We currently don't have a mechanism for secrets.

Set up rate limitting with Geoip database

---

README.md
group_vars/all.yml

- Follow up from https://github.com/ceresfairfood/fairfood-install/pull/46
I just realised that PR only  updated the config for metabase 🤦

Enable geoip rate limit for fairfood_https

---

roles/fairfood/templates/post-receive.j2

- https://github.com/ceresfairfood/fairfood-issues/issues/2670
Add explicit success message for local deploy script to discern success from failure. If any command in the script fails, the script stops and the success message is never printed.

Update post-receive hook
